# triggers
# 1. Push, manual trigger
# Jobs:
# 1. Test and lint the project 
# 2. Build Project
name: FirstWorkflow
on: [push, workflow_dispatch]

jobs:
  moduleInstallation:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Dependencies Installation Job Complete
        run: echo "Module Installation Done"  
        
  Test:
    needs: moduleInstallation
    runs-on: ubuntu-latest
    steps:
      - name: Run test command
        run: npm run test
      - name: Testing Complete
        run: echo "Test command execution completed"

  Build:
    needs: [moduleInstallation,Test]
    runs-on: ubuntu-latest
    steps: 
      - name: Build Project
        run: npm run build
      
    
